Reelae/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Reelae.Filters;
using Reelae.Repositories;
using Reelae.Utilities;

namespace Reelae.Controllers
{
    [Authorize]
    [checkSessionAlive]
    public class ChatController : Controller
    {
        // GET: Chat
        private HttpContextBase currentContext = null;
        IChatRepository _chatRepo;

        public ChatController(IChatRepository __chatRepo)
        {
            _chatRepo = __chatRepo;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ResumableUploader()
        {
            currentContext = Request.RequestContext.HttpContext;
            if (Request.RequestType.ToUpper() == "GET")
            {
                var queryString = currentContext.Request.QueryString;
                var resumableFilename = queryString.Get("resumableFilename");
                if (!FileUtility.IsValidFileForUpload(resumableFilename))
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid File Type");
                bool result = UploadFile();
                if (result)
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                else
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            else if (Request.RequestType.ToUpper() == "POST")
            {
                var queryString = currentContext.Request.QueryString;
                var resumableFilename = queryString.Get("resumableFilename");
                if (!FileUtility.IsValidFileForUpload(resumableFilename))
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid File Type");
                else
                    return UploadFile(Request.InputStream);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        public ActionResult DownloadFile()
        {
            currentContext = Request.RequestContext.HttpContext;
            var queryString = currentContext.Request.QueryString;
            if (queryString.Count == 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var filePath = queryString.Get("fP");
            var fileName = queryString.Get("fN");
            if (!string.IsNullOrEmpty(filePath))
            {
                var localFilePath = currentContext.Server.MapPath(filePath);
                var fileInfo = new System.IO.FileInfo(localFilePath);
                if (fileInfo.Exists)
                {
                    currentContext.Response.ContentType = System.Net.Mime.MediaTypeNames.Application.Octet;
                    currentContext.Response.AddHeader("Content-disposition", "attachment; filename=" + fileName);
                    currentContext.Response.TransmitFile(localFilePath);
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
                }
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        private bool UploadFile()
        {
            string _uploadFolder = "ResumableUpload";
            var queryString = currentContext.Request.QueryString;
            if (queryString.Count == 0) return false;

            // Read parameters
            var uploadToken = queryString.Get("upload_Token");

            int resumableChunkNumber = int.Parse(queryString.Get("resumableChunkNumber"));
            var resumableIdentifier = queryString.Get("resumableIdentifier");
            //var resumableChunkSize = queryString.Get("resumableChunkSize");
            //var resumableTotalSize = queryString.Get("resumableTotalSize");
            var resumableFilename = queryString.Get("resumableFilename");
            uploadToken = (string.IsNullOrEmpty(uploadToken)) ? resumableIdentifier : "";
            var filePath = string.Format("{0}/{1}/{1}.part{2}", _uploadFolder,
                           uploadToken, resumableChunkNumber.ToString("0000"));
            var localFilePath = currentContext.Server.MapPath(filePath);

            // Response
            var fileExists = System.IO.File.Exists(localFilePath);
            return fileExists;
        }

        private ActionResult UploadFile(object data)
        {

            try
            {
                var queryString = currentContext.Request.Form;
                if (queryString.Count == 0) new HttpStatusCodeResult(HttpStatusCode.NotFound);
                string _uploadFolder = "~/ChatUploads";
                // Read parameters
                var uploadToken = queryString.Get("upload_Token");
                int resumableChunkNumber = int.Parse(queryString.Get("resumableChunkNumber"));
                var resumableFilename = queryString.Get("resumableFilename");
                var resumableIdentifier = queryString.Get("resumableIdentifier");
                int resumableChunkSize = int.Parse(queryString.Get("resumableChunkSize"));
                long resumableTotalSize = long.Parse(queryString.Get("resumableTotalSize"));

                uploadToken = (string.IsNullOrEmpty(uploadToken)) ? resumableIdentifier : "";

                var filePath = string.Format("{0}/{1}/{1}.part{2}", _uploadFolder,
                                      uploadToken, resumableChunkNumber.ToString("0000"));
                var localFilePath = currentContext.Server.MapPath(filePath);
                var directory = System.IO.Path.GetDirectoryName(localFilePath);
                if (!System.IO.Directory.Exists(localFilePath)) System.IO.Directory.CreateDirectory(directory);

                if (currentContext.Request.Files.Count == 1)
                {
                    // save chunk
                    if (!System.IO.File.Exists(localFilePath))
                    {
                        currentContext.Request.Files[0].SaveAs(localFilePath);
                    }

                    // Check if all chunks are ready and save file
                    var files = System.IO.Directory.GetFiles(directory);
                    if ((files.Length + 1) * (long)resumableChunkSize >= resumableTotalSize)
                    {
                        filePath = string.Format("{0}/{1}{2}", _uploadFolder,
                          System.IO.Path.GetFileNameWithoutExtension(resumableFilename) + "_" + DateTime.Now.Ticks.ToString(), System.IO.Path.GetExtension(resumableFilename));
                        localFilePath = currentContext.Server.MapPath(filePath);
                        using (var fs = new FileStream(localFilePath, FileMode.CreateNew))
                        {
                            foreach (string file in files.OrderBy(x => x))
                            {
                                var buffer = System.IO.File.ReadAllBytes(file);
                                fs.Write(buffer, 0, buffer.Length);
                                System.IO.File.Delete(file);
                            }
                        }
                        System.IO.Directory.Delete(directory);
                        //after save details in db also and send the final identifier

                        Response.Write("filePath=" + Url.Content(filePath) + "");
                    }
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
                else
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }


        [ValidateInput(false)]
        public ActionResult ExportChat(string userId, string userName)
        {
            int _userid = Session["UserId"] != null ? Convert.ToInt32(Session["UserId"]) : 0;
            string Html = GetChatExportData(_userid, Convert.ToInt32(userId), userName);
            var htmlContent = String.Format("<body>Hello world: {0}</body>",
        DateTime.Now);
            var htmlToPdf = new NReco.PdfGenerator.HtmlToPdfConverter();
            var pdfBytes = htmlToPdf.GeneratePdf(Html);
            return File(pdfBytes, "application/pdf", "ChatHistroy_" + DateTime.Now.ToShortDateString() + ".pdf");
        }


        public ActionResult ExportCsvChat(string userId, string userName)
        {
            int _userid = Session["UserId"] != null ? Convert.ToInt32(Session["UserId"]) : 0;
            string Html = GetChatExportDataForCsv(_userid, Convert.ToInt32(userId), userName);
            return Json(new
            {
                status = MasterConstants.SUCCESSTITLE,
                msg = MasterConstants.SAVESUCCESSFULLY,
                Data = Html,
            }, JsonRequestBehavior.AllowGet);
        }



        private string GetFileType(string type)
        {
            string result = "";
            int lastIndexOfDot = type.LastIndexOf('.');
            string extension = type.Substring(lastIndexOfDot + 1, type.Length - lastIndexOfDot - 1).ToLower();

            if (extension == "pdf" || extension == "doc" || extension == "docx" || extension == "txt" || extension == "rtf" || extension == "zip" || extension == "rar")
            {
                result = "doc";
            }
            else if (extension == "png" || extension == "jpg" || extension == "jpeg" || extension == "gif" || extension == "tif")
            {
                result = "image";
            }
            else if (extension == "mp3" || extension == "obb" || extension == "wave")
            {
                result = "audio";
            }

Reelae/Areas/Student/Views/Shared/_ChatMembersLists.cshtml
@model IEnumerable<ReelaeDataAccessLayer.re_GetChatMembers_sp_Result>
@{
    var members = Model.ToList();
    var uEmail = User.Identity.Name;
    var usersUnreadMessages = ((List<ReelaeDataAccessLayer.re_getUserSingleChatUnreadMessagesCount_sp_Result>)ViewBag.UesrsUnreadMessagesWithCount);
}
@helper GetUserPic(string _userType, string picUrl)
{
if (!string.IsNullOrEmpty(picUrl))
{
        <img src="@Url.Content(picUrl)" class="img-responsive">
}
else
{
    if (string.IsNullOrEmpty(_userType))
    {
            <img src="@Url.Content("~/content/images/user.png")" class="img-responsive">
    }
    else
    {
        if (_userType.ToLower() == "t")
        {
                <img src="@Url.Content("~/content/images/teacher.jpg")" class="img-responsive">

        }
        else if (_userType.ToLower() == "s")
        {
                <img src="@Url.Content("~/content/images/student.jpg")" class="img-responsive">
        }
        else
        {
                <img src="@Url.Content("~/content/images/user.png")" class="img-responsive">
        }
    }
}

}

@helper GetUserUnreadNotification(int UserId, IEnumerable<ReelaeDataAccessLayer.re_getUserSingleChatUnreadMessagesCount_sp_Result> _usersUnreadMessagesLists)
{

    if (_usersUnreadMessagesLists.Any(n => n.FromUserID == UserId))
    {
        int? _count = _usersUnreadMessagesLists.Where(n => n.FromUserID == UserId).First().UnreadMsgCount;
        if (_count.HasValue && _count.Value > 0)
        {
                <span class="chat_icn-wrap bg-noti">@_count</span>
        }
        else
        {
                <span style="display:none" class="chat_icn-wrap bg-noti"></span>

        }

    }
    else
    {
            <span style="display:none" class="chat_icn-wrap bg-noti"></span>

    }

}

@foreach (var item in members)
{
    string userName = (item.Name.Length > 15) ? item.Name.Substring(0, 12) + ".." : item.Name;
    if (uEmail == item.Email)
    {
        continue;
    }
    <div class="user_chat-detail" style="cursor:pointer;" uEId="@item.Email" userToken="@item.UserID" cT="single">
        <div class="user_pic">@GetUserPic(item.UserType, item.UserPicUrl)@GetUserUnreadNotification(item.UserID, usersUnreadMessages)</div>
        <div class="chat-user_name">
            <h2 class="name" title="@item.Name">
                @userName
                @*<div class="clearfix"></div>
                    <small>@item.ChatStatus</small>*@
            </h2>
        </div>
        <div class="user_status"><i class="fa fa-circle @((item.IsOnline==1) ?"txt_on":"txt_off") aria-hidden=" true"></i></div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
}

Reelae/Areas/Student/Views/Shared/_IndividualChatBody.cshtml
@model IEnumerable<ReelaeDataAccessLayer.re_GetSingleChatBody_sp_Result>
@{
    var UserID = Session["UserId"] as int?;
    var curType = "text";
    bool isSent = false;
    bool isUnreadLabelCreated = false;
}
@helper GetFileExtention(string fileName)
{
int lastIndexOfDot = fileName.LastIndexOf('.');
string extension = fileName.Substring(lastIndexOfDot + 1, fileName.Length - lastIndexOfDot - 1).ToLower();
    @extension
}

@helper GetFileType(string type)
{
int lastIndexOfDot = type.LastIndexOf('.');
string extension = type.Substring(lastIndexOfDot + 1, type.Length - lastIndexOfDot - 1).ToLower();

if (extension == "pdf" || extension == "doc" || extension == "docx" || extension == "txt" || extension == "rtf" || extension == "zip" || extension == "rar")
{
        @:doc
    }
    else if (extension == "png" || extension == "jpg" || extension == "jpeg" || extension == "gif" || extension == "tif")
    {
        @:image
    }
    else if (extension == "mp3" || extension == "obb" || extension == "wave")
    {
        @:audio
    }
else if (extension == "mp4" || extension == "avi" || extension == "wmv" || extension == "flv")
{
        @:video
    }
    else
    {
        @:text
    }

}
@foreach (var item in Model)
{
    string addonClass = "";
    string downloadUrl = Url.Action("DownloadFile", "Chat", new { area = "" });
    string timeString = "";
    curType = (item.IsAttachment) ? GetFileType(item.MessageText).ToHtmlString().Trim() : "text";
    bool isUnreadMessages = item.IsRead == 0;

    if (item.FromUserID == UserID)
    {
        addonClass = " bubble_chat-alt white";
        isSent = true;
        timeString = "Delivered";
    }
    else
    {
        isSent = false;
        timeString = "Sent " + item.MessageDate.Value.ToShortTimeString();
    }

    if (isUnreadMessages && !isUnreadLabelCreated)
    {
        isUnreadLabelCreated = true;
        int? _count = ViewBag.UnreadMessagesCount as int?;
        if (_count.HasValue && _count.Value > 0)
        {
            <div class="clearfix"></div>
            <div class="time_bar unread" style="font-weight:bold;color:#000"><span>@(_count) Unread Messages</span></div>
            <div class="clearfix"></div>
        }
    }

    if (curType == "text")
    {
        <div msgToken="@item.MessageID" class="bubble_chat@(addonClass)">
            <i title="remove this message" class="material-icons cancel_chat">cancel</i>
            <p>@Html.Raw(item.MessageText)</p>
            <span class="time">@timeString</span>
        </div>
    }
    else if (curType == "image")
    {
        downloadUrl += "?" + string.Format("fP={0}&fN={1}", item.AttachmentURL, item.MessageText);
        <div msgToken="@item.MessageID" class="bubble_chat@(addonClass)">
            <i title="remove this message" class="material-icons cancel_chat">cancel</i>
            <a class="fileView" target="_blank" href="@Url.Content(downloadUrl)">
                <p><img src="@Url.Content(item.AttachmentURL)" alt="..." class="img-responsive"></p>
                <span class="time">@timeString</span>
            </a>
        </div>
    }
    else if (curType == "video")
    {
        downloadUrl += "?" + string.Format("fP={0}&fN={1}", item.AttachmentURL, item.MessageText);
        <div msgToken="@item.MessageID" class="bubble_chat@(addonClass)">
            <i title="remove this message" class="material-icons cancel_chat">cancel</i>
            <a class="fileView" target="_blank" href="@Url.Content(downloadUrl)">
                <p>
                    <video class="img-responsive" id="thumb">
                        <source src="@item.AttachmentURL" />
                    </video>
                    <span class="time">@timeString</span>
                </p>
            </a>
        </div>
    }
    else if (curType == "audio")
    {
        downloadUrl += "?" + string.Format("fP={0}&fN={1}", item.AttachmentURL, item.MessageText);
        <div msgToken="@item.MessageID" class="bubble_chat@(addonClass)">
            <i title="remove this message" class="material-icons cancel_chat">cancel</i>
            <a class="fileView" target="_blank" href="@Url.Content(downloadUrl)">
                <p>
                    <audio controls>
                        <source src="@item.AttachmentURL" />
                    </audio>
                    <span class="time">@timeString</span>
                </p>
            </a>
        </div>
    }
    else if (curType == "doc")
    {
        downloadUrl += "?" + string.Format("fP={0}&fN={1}", item.AttachmentURL, item.MessageText);
        var fileName = (item.MessageText.Length > 35) ? (item.MessageText.Substring(0, 32) + "...") : item.MessageText;

        <div msgToken="@item.MessageID" class="bubble_chat@(addonClass)">
            <i title="remove this message" class="material-icons cancel_chat">cancel</i>
            <p>
                <a title="@item.MessageText" class="fileView chat_attachment bg_org" target="_blank" href="@Url.Content(downloadUrl)">

                    <i class="material-icons">attachment</i> <span class="attachment_txt "> @fileName</span>
                </a>
                @*<a class="fileView" target="_blank" href="@Url.Content(downloadUrl)">
                        <div class="prod_box text-center">
                            <div class="prod_wrap bg_org slide">
                                <i class="material-icons file_icn">insert_drive_file</i>
                                <span class="file_type-txt">.xls</span>
                            </div>
                            <div class="prod_detail">
                                <span>
                                    @item.MessageText
                                </span>
                            </div>
                        </div>
                    </a>*@
            </p>
            <span class="time">@timeString</span>
        </div>
    }

}

Reelae/Areas/Student/Views/Shared/_RTE_MemberEditingSection.cshtml
@model ReelaeDataAccessLayer.re_getAssignmentWorkspaceContent_sp_Result

<div class="usereditwrap @ViewBag.userCls" sid="@Model.StudentID">
    <input type="hidden" name="lastUpdatedOn" value="@Model.ModifiedDate" />
    <input type="hidden" name="hdnUserSN" value="@(string.IsNullOrEmpty(ViewBag.useShortName)?Model.Name.ToUpper()[0]:ViewBag.useShortName)" />
    <input type="hidden" name="hdnUserPicUrl" value="@(string.IsNullOrEmpty(ViewBag.userPicUrl)?"":Url.Content(ViewBag.userPicUrl))" />
    <div class="col-md-2 userName">
        @Model.Name
        <br />
        <small>
            @(Model.WordCount ?? 0) / @ViewBag.PerWordsGoal
        </small>
    </div>
    <div class="col-md-10 editableCon">
        @if (string.IsNullOrEmpty(Model.Content))
        {
            <p placeholder>
                please enter assignment note here
            </p>
        }
        else
        {
            <p>
                @Html.Raw(Model.Content)
            </p>
        }
    </div>
</div>