Reelae/Controllers/UserProfileController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Reelae.Models;
using ReelaeDataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reelae.Repositories;
using Reelae.Filters;
using System.IO;
using ReelaeBusinessLayer.Utilities;
using Reelae.Utilities;

namespace Reelae.Controllers
{
    [Authorize]
    [checkSessionAlive]
    public class UserProfileController : Controller
    {
        private ApplicationUserManager _userManager;
        IUserRepository _userRepo;
        ILogRepository _dbLogrepo;
        IAspnetUsersRepository _aspnetuserRepo;
        // GET: UserProfile

        public UserProfileController(IUserRepository __userRepo, ILogRepository __dbLogrepo, IAspnetUsersRepository __aspnetuserRepo)
        {
            _userRepo = __userRepo;
            _dbLogrepo = __dbLogrepo;
            _aspnetuserRepo = __aspnetuserRepo;

        }

        public UserProfileController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ActionResult Index()
        {

            return View();
        }


        public ActionResult ProfileSetup()
        {
            try
            {
                ViewBag.PageHeading = "Profile Setting";
                User model = _userRepo.Get(Convert.ToInt32(Session["UserId"]));
                if (model.Website == null)
                {
                    model.Website = "http://";
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                return RedirectToAction("Login");
            }


        }

        [HttpPost]
        public JsonResult SaveProfile(User model)
        {
            if (ModelState.IsValidField("Email") && ModelState.IsValidField("Name"))
            {
                if (model.Website == "http://" || model.Website == "https://")
                {
                    model.Website = null;
                    _userRepo.Update(model, Session["UserName"].ToString());
                    _aspnetuserRepo.update(User.Identity.GetUserId(), model.Name);
                    Session["Name"] = model.Name;

                    return this.Json(new
                    {
                        EnableSuccess = true,
                        SuccessTitle = MasterConstants.SUCCESSTITLE,
                        SuccessMsg = MasterConstants.PROFILESAVESUCCESS
                    });
                }
                else
                {
                    if (ModelState.IsValidField("Website"))
                    {
                        _userRepo.Update(model, Session["UserName"].ToString());
                        _aspnetuserRepo.update(User.Identity.GetUserId(), model.Name);
                        Session["Name"] = model.Name;

                        return this.Json(new
                        {
                            EnableSuccess = true,
                            SuccessTitle = MasterConstants.SUCCESSTITLE,
                            SuccessMsg = MasterConstants.PROFILESAVESUCCESS
                        });
                    }
                    else
                    {
                        var error = this.ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.First().ErrorMessage;
                        return this.Json(new
                        {
                            EnableError = true,
                            ErrorTitle = MasterConstants.ERRORTITLE,
                            ErrorMsg = error
                        });
                    }
                }
            }
            else
            {
                var error = this.ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.First().ErrorMessage;
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = error
                });
            }
        }
        public ActionResult GetChangePasswordView()
        {
            try
            {
                return PartialView("ChangePassword", new Reelae.Models.ChangePasswordViewModel());
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                return RedirectToAction("Login");
            }

        }
        public ActionResult GetProfileSetupView()
        {
            try
            {
                User model = _userRepo.Get(Convert.ToInt32(Session["UserId"]));
                return PartialView("UserProfileSetup", model);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                return RedirectToAction("Login");
            }

        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        public JsonResult ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var error = this.ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.First().ErrorMessage;
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = error
                });
            }
            var result = UserManager.ChangePassword(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                return this.Json(new
                {
                    EnableSuccess = true,
                    SuccessTitle = MasterConstants.SUCCESSTITLE,
                    SuccessMsg = MasterConstants.PASSWORDCHANGESUCCESS
                });

            }

            else
            {
                if (result.Errors.First().StartsWith("Passwords must have at least"))
                {
                    return this.Json(new
                    {
                        EnableError = true,
                        ErrorTitle = MasterConstants.ERRORTITLE,
                        ErrorMsg = MasterConstants.PASSWORDVALIDATIONVIEWMESSAGE
                    });
                }
                else
                {
                    return this.Json(new
                    {
                        EnableError = true,
                        ErrorTitle = MasterConstants.ERRORTITLE,
                        ErrorMsg = MasterConstants.OLDPASSWORDINCORRECT
                    });
                }
            }

        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [HttpPost]
        public ActionResult UploadPic()
        {
            // Checking no of files injected in Request object  
            string fname = "";
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.  
                        Random rnd = new Random();
                        fname = "UserPhoto_" + rnd.Next(1000) + "_" + Session["UserId"].ToString() + System.IO.Path.GetExtension(fname);
                        //fname = Path.Combine(Server.MapPath("~/InstituteLogo/"), fname);
                        file.SaveAs(Path.Combine(Server.MapPath("~/UserPic/"), fname));
                    }
                    // Returns message that successfully uploaded  
                    //return Json(fname);
                    return Json(new
                    {

Reelae/Views/Shared/ChangePassword.cshtml
@model  Reelae.Models.ChangePasswordViewModel
@using (Ajax.BeginForm("ChangePassword", "UserProfile", new AjaxOptions { HttpMethod = "Post", OnSuccess = "onPasswordSucess", OnFailure = "onPasswordFailure", OnBegin = "return ValidateFields();" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })


    <div class="form-group">
        <label for="Email">Current Password</label>
        @Html.PasswordFor(model => model.OldPassword, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="Email">New password</label>
        @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="Email">Confirm new password</label>
        @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
    </div>
    @*<input type="button" class="button_blue" onclick="ValidateFields();" value="Change Password" />
        <input id="submitChangePasword" style="display:none;" type="submit" data-toggle="modal" class="modal-footer" value="" />*@
    <div class="clearfix"></div>
    @*<input value="Submit" class="button_blue button_100" type="submit" />*@
    <input type="submit" value="Submit" class="button_blue col-sm-6 width_2-btn marg_l-20">
    @Html.ActionLink("Cancel", "Cancel", "", new { @class = "button_blue btn_no col-sm-6 width_2-btn pull-right marg_r-20" })
}

Reelae/Views/Shared/UserProfileSetup.cshtml
@model ReelaeDataAccessLayer.User
@using (Ajax.BeginForm("SaveProfile", "UserProfile", new AjaxOptions { HttpMethod = "Post", OnSuccess = "onProfileSucess", OnFailure = "onProfileFailure", OnBegin = "return ValidateProfileFields();" },new { @id="divUserProfile" }))
{
    <div class="logo_wrapper">
        <div class="upload_logo">
            @if (Model.UserPicUrl != null)
            {
                <img src="@Url.Content(Model.UserPicUrl)" alt="..." class="img-responsive" id="imgUserPic">

            }
            else
            {
                <img src="" alt="..." class="img-responsive" id="imgUserPic">

            }
        </div>
        <div class="hiddenfile">
            <input name="upload" type="file" id="FileUpload1" onchange="UploadPic();" />
        </div>
        @Html.HiddenFor(model => model.UserPicUrl)
        @Html.HiddenFor(model => model.UserID)
        <a href="#!" class="gr_btn brd_radius-4" onclick="triggerFileUpload()">Upload New</a>
        <a href="#!" class="red_btn brd_radius-4" onclick="DeletePic()">Delete</a>
    </div>
    <div class="clearfix"></div>
    <div class="gap_30"></div>
    <div class="form-group">
        <label>Name</label><span style="color:red;font-size: 12px;">*</span>
        <div class="clearfix"></div>
        @Html.TextBoxFor(model => model.Name, new { maxlength = "25", @class = "form-control brd_radius-4", onchange = "onChangeValidate(this)" })
    </div>
    <div class="gap_20"></div>
    <div class="form-group">
        <label>Surname</label>
        <div class="clearfix"></div>
        @Html.TextBoxFor(model => model.Surname, new { maxlength = "25", @class = "form-control brd_radius-4", onchange = "onChangeValidate(this)" })
    </div>
    <div class="gap_20"></div>
    <div class="form-group">
        <label>Email</label>
        <div class="clearfix"></div>
        @Html.TextBoxFor(model => model.Email, new { maxlength = "256", @class = "form-control brd_radius-4", onchange = "onChangeValidate(this)" })
    </div>
    <div class="gap_20"></div>
    <div class="form-group">
        <label>Location</label>
        <div class="clearfix"></div>
        @Html.TextBoxFor(model => model.Location, new { maxlength = "50", @class = "form-control brd_radius-4" , onchange = "onChangeValidate(this)" })
    </div>
    <div class="gap_20"></div>
    <div class="form-group">
        <label>Website</label>
        <div class="clearfix"></div>
        @Html.TextBoxFor(model => model.Website, new { maxlength = "256", @class = "form-control brd_radius-4" , onchange = "onChangeValidate(this)" })
        <span style="color:red;font-size: 12px;">*Website should contain "http://" or "https://"</span>
    </div>
    <div class="gap_20"></div>
    <div class="form-group">
        <label>Bio</label>
        <div class="clearfix"></div>
        @*@Html.TextAreaFor(model => model.BIO, new { @class = "form-control brd_radius-4" })*@
        <textarea class="form-control brd_radius-4" cols="20" id="BIO" name="BIO" rows="6" maxlength = "150" onchange="onChangeValidate(this)" style="resize: none;">@Model.Bio</textarea>
    </div>
    <div class="gap_20"></div>
    @*<a href="#!" class="bottom_btn mrg-lbr-20">Save Changes</a>*@
    <input type="submit" value="Save Changes" class="button_blue col-sm-6 width_2-btn marg_l-20">
    @Html.ActionLink("Cancel", "Cancel", "", new { @class = "button_blue btn_no col-sm-6 width_2-btn pull-right marg_r-20" })
    <div class="clearfix"></div>
}

Reelae/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reelae</title>
    <link rel="shortcut icon" type="image/png" href="~/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet" />
    <!--New Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/media.css">
    <link href="@Url.Content("~/Content/css/Loader.css")" rel="stylesheet" />
    <style type="text/css">
        .message {
          color:  #a94442;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="col-md-12 wrap">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="@Url.Content("~/Content/images/logo.jpg")" alt="Logo"></a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav pull-right">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">Pricing</a></li>
                    <li><a href="#contact">About Us</a></li>
                    <li>@Html.ActionLink("Login", "login", "Home", new { id = "l" }, null)</li>
                    <li>@Html.ActionLink("Sign Up", "login", "Home", new { id = "s" }, null)</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container wrap mt-50">
        @RenderBody()
    </div>

    <div class="circle_loader" id="divLoader" style="display:none;">
        <div class="circle__item">
            <svg class="circle__spinner" viewBox="0 0 50 50">
                <circle class="path" cx="25" cy="25" r="20" fill="none" stroke="#93bfec" stroke-width="1"></circle>
            </svg>
        </div>
    </div>
    <!--Generic Alert Box-->
    <div class="modal" id="genericAlertBox" tabindex="-1" role="dialog" aria-labelledby="genericAlertBoxModalLabel">
        <div class="modal-dialog" role="document" style="width:420px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="btnCloseModal"><i class="material-icons">clear</i></button>
                    <h4 class="modal-title" style="color:#fff" id="genericAlertBoxModalLabel">Alert Message</h4>
                </div>
                <div class="modal-body">
                    <div class="col-sm-10 col-sm-offset-1" style="margin: 0 auto; float: none;">
                        <p class="popup_txt" style="text-align: center;font-weight: 600;">Perfect! Now teacher can interact with students attendance in his dashboard.</p>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!--Common Utility-->
    <script src="@Url.Content("~/Content/admin/js/adminutility.js")"></script>
    @RenderSection("custom_scripts", false)
</body>
</html>