Reelae/Areas/Student/Models/MilestonesViewModel.cs
using ReelaeDataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reelae.Areas.Student.Models
{
    public class MilestonesViewModel
    {
        public User _userinfo { get; set; }

        public IEnumerable<re_getStudentAssignment_sp_Result> assignments { get; set; }
    }
}

Reelae/Areas/Student/Models/newMilestoneViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ReelaeDataAccessLayer;

namespace Reelae.Areas.Student.Models
{
    public class newMilestoneViewModel
    {
        public MileStone milestone { get; set; }

       public IEnumerable<re_getAssignmentMember_sp_Result> Memebers { get; set; }
    }
}

Reelae/Areas/Student/Controllers/MileStonesController.cs
using Reelae.Repositories;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reelae.Areas.Student.Models;
using Reelae.Filters;
using ReelaeBusinessLayer.Utilities;
using Reelae.Utilities;
using System.IO;
using ReelaeDataAccessLayer;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;

namespace Reelae.Areas.Student.Controllers
{

    [LoggingFilter]
    [checkSessionAlive]
    [Authorize(Roles = "Student")]
    public class MileStonesController : Controller
    {
        IUserRepository _userRepo;
        ILogRepository _dbLogrepo;
        IMilestoneRepository _milestoneRepo;

        public MileStonesController(IUserRepository __userRepo, ILogRepository __dbLogrepo, IMilestoneRepository __milestoneRepo)
        {
            _userRepo = __userRepo;
            _dbLogrepo = __dbLogrepo;
            _milestoneRepo = __milestoneRepo;

        }

        // GET: Student/MileStones
        public ActionResult Index()
        {
            try
            {
                MilestonesViewModel model = new MilestonesViewModel();
                int? _studentId = Session["UserId"] as int?;
                int? _InstutionID = Session["Institution"] as int?;
                model._userinfo = _userRepo.Get(User.Identity.GetUserId());
                model.assignments = _milestoneRepo.GetAssignments(_studentId);
                ViewBag.PageHeading = "Milestones";
                return View(model);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                return this.Json(new
                {
                    status = MasterConstants.FAILURETITLE,
                    msg = MasterConstants.SOMEPROBLEMOccurred,
                    Data = string.Empty
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult getStudents(DateTime startDate, DateTime endDate, int assignmentId)
        {
            try
            {
                List<MilestoneStudentsData> _students = new List<MilestoneStudentsData>();
                //var _data = _milestoneRepo.getMilestoneStudents(startDate.Date, endDate.Date, assignmentId).ToList();
                _milestoneRepo.getMilestoneStudents(startDate.Date, endDate.Date, assignmentId).ToList().ForEach(std => _students.Add(new MilestoneStudentsData() { id = std.StudentId.Value, name = std.StudentName, pic = Url.Content(std.UserPicUrl) }));
                //_students.ForEach(r => r.UserPicUrl = Url.Content(r.UserPicUrl));
                return Json(_students);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserName"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = MasterConstants.SOMEPROBLEMOccurred
                }, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpPost]
        public ActionResult getData(DateTime startDate, DateTime endDate, int assignmentId)
        {
            try
            {
                List<taskData> _data = new List<taskData>();
                _milestoneRepo.getMilestoneData(startDate.Date, endDate.Date, assignmentId).ToList().ForEach(d => _data.Add(new taskData()
                {
                    studentId = d.StudentId,
                    text = d.MileStoneName,
                    pic = d.User.UserPicUrl != null ? Url.Content(d.User.UserPicUrl) : Url.Content("~/Content/images/student.jpg"),
                    startDateYear = d.StartDate.Year,
                    startDateMonth = (d.StartDate.Month - 1),
                    startDateDay = d.StartDate.Day,
                    startDateHour = d.StartDate.Hour,
                    startDateMin = d.StartDate.Minute,
                    endDateYear = d.endDate.Year,
                    endDateMonth = (d.endDate.Month - 1),
                    endDateDay = d.endDate.Day,
                    endDateHour = d.endDate.Hour,
                    endDateMin = d.endDate.Minute,
                    milestoneId = d.MileStoneID,
                    startDateInfo = d.StartDate.ToString("dd MMM yyyy hh:mm tt"),
                    endDateInfo = d.endDate.ToString("dd MMM yyyy hh:mm tt"),
                    TaskDescription = d.TaskDescription,
                    MilesStoneStatus = d.MilesStoneStatus
                }));
                return Json(_data);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserName"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = MasterConstants.SOMEPROBLEMOccurred
                }, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpPost]
        public ActionResult getNewMilestoneView(int id)
        {

            try
            {
                newMilestoneViewModel model = new newMilestoneViewModel();
                ViewBag.AssignmentDueDate = _milestoneRepo.getAssignmentDate(id).Value;
                ViewBag.AssignmentName = _milestoneRepo.getAssignmentName(id);
                model.Memebers = _milestoneRepo.GetAssignmentMembers(id).ToList();
                model.milestone = new MileStone() { AssignmentID = id, StudentId = model.Memebers.First().MemberId };
                return PartialView("_newMilestone", model);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                return this.Json(new
                {
                    status = MasterConstants.FAILURETITLE,
                    msg = MasterConstants.SOMEPROBLEMOccurred,
                    Data = string.Empty
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult geteditMilestoneView(int id)
        {

            try
            {
                newMilestoneViewModel model = new newMilestoneViewModel();
                model.milestone = _milestoneRepo.GetMilestone(id);
                ViewBag.AssignmentDueDate = _milestoneRepo.getAssignmentDate(model.milestone.AssignmentID.Value).Value;
                ViewBag.AssignmentName = _milestoneRepo.getAssignmentName(model.milestone.AssignmentID.Value);
                model.Memebers = _milestoneRepo.GetAssignmentMembers(model.milestone.AssignmentID.Value).ToList();
                return PartialView("_newMilestone", model);
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserId"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message };
                return this.Json(new
                {
                    status = MasterConstants.FAILURETITLE,
                    msg = MasterConstants.SOMEPROBLEMOccurred,
                    Data = string.Empty
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult addNewMilestone(newMilestoneViewModel model)
        {
            try
            {
                if (model.milestone.MileStoneID == 0)
                {
                    if (ModelState.IsValid)
                    {
                        model.milestone.MilesStoneStatus = 1;
                        _milestoneRepo.Add(model.milestone, Session["UserName"].ToString());
                        return this.Json(new
                        {
                            EnableSuccess = true,
                            SuccessTitle = MasterConstants.SUCCESSTITLE,
                            SuccessMsg = MasterConstants.SAVESUCCESSFULLY
                        });
                    }
                    else
                    {
                        var error = this.ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.First().ErrorMessage;
                        return this.Json(new
                        {
                            EnableError = true,
                            ErrorTitle = MasterConstants.ERRORTITLE,
                            ErrorMsg = error
                        });
                    }
                }
                else
                {

Reelae/Areas/Student/Views/MileStones/Index.cshtml
@model Reelae.Areas.Student.Models.MilestonesViewModel
@{
    ViewBag.Title = "Milestones";
    Layout = "~/Areas/Student/Views/Shared/_StudentLayout.cshtml";
    var _user = Model._userinfo;
    var _assignments = Model.assignments.ToList();
    string curAssignemnt = "0";
    if (_assignments != null && _assignments.Count() > 0)
    {
        curAssignemnt = Url.RequestContext.RouteData.Values["id"] != null ? Url.RequestContext.RouteData.Values["id"].ToString() : _assignments.First().AssignmentID.ToString();
    }
    int? _CurstudentId = Session["UserId"] as int?;


}
@section head{
    <script src="@Url.Content("~/content/Student/js/Milestones.js")"></script>
    <script>
        var _CurstudentId = '@_CurstudentId';
    </script>
    <style>
        .user-profile img {
            height: 22px;
            width: 22px;
            position: relative;
            top: -2px;
        }

        .mad-select li {
            height: 27px;
        }

        /*.dx-scheduler-timeline .dx-scheduler-header-panel-cell, .dx-scheduler-timeline .dx-scheduler-date-table-cell {
            width: 100px;
        }*/

        /*.dx-scheduler-header-panel-cell {
            width: 1400px !important;
        }*/
    </style>
}

@section InstitueName{
    @Html.Partial("~/Areas/Admin/Views/Shared/_InstituteSetupHeader.cshtml", _user)
}
@section UserProfile{
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        @if (Model._userinfo.UserPicUrl != null && Model._userinfo.UserPicUrl != "")
        {
            <img src="@Url.Content(Model._userinfo.UserPicUrl)" alt="" />
        }
        Hello, @Reelae.Utilities.CommonUtility.ToTitleCase(Session["Name"].ToString().ToLower()) <span class="fa fa-angle-down"></span>
    </a>

}
<!-- page content -->
<div class="right_col pd_l-0 height_vh bg_white pd_b-0" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 mrg_t_10 mob-mrg">
            <div class="dashboard_graph pd_b-0 brd_bottom">
                <div class="row x_title mrb_b-0">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <h3 style="float:left; padding-right:10px;">Milestones</h3>
                        <div id="dateFilterEle" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #969696; border-radius: 4px;float:left;display:block">
                            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i> <span></span> <b class="caret"></b>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 text-right xs-left pad_r25">
                        <div class="mad-select" style="margin-left:0px;width:200px;">
                            <ul id="ddlMember">
                                @if (_assignments != null && _assignments.Count() > 0)
                                {
                                    foreach (var _assignment in _assignments)
                                    {
                                        <li data-value="@_assignment.AssignmentID" onclick="milestone(@_assignment.AssignmentID)">@_assignment.AssignmentName</li>
                                    }
                                }
                                else
                                {
                                    <li data-value="0">No assignments yet</li>
                                }
                            </ul>
                            <input type="hidden" name="selAssignment" id="selAssignment" value="@curAssignemnt">
                        </div>
                        <a href="#!" class="btn_blue mml-0 min_w-155 text-center" onclick="getNewMilestoneView(@_assignments.Count())">+ Add Milestone</a>
                    </div>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="dx-viewport demo-container">
        <div id="scheduler"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- /page content -->

Reelae/Areas/Student/Views/MileStones/_editMilestoneStatus.cshtml
@model ReelaeDataAccessLayer.MileStone
<div class="modal" id="milestoneStatusModelBox" tabindex="-1" role="dialog" aria-labelledby="milestoneStatusLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="material-icons">clear</i></button>
                <h4 class="modal-title" id="milestoneStatusLabel">@Model.MileStoneName</h4>
            </div>
            @using (Ajax.BeginForm("saveMilestoneStatus", "MileStones", new { area = "Student" }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "onSaveStatusSucess", OnFailure = "", OnBegin = "" }))
            {
                <div class="modal-body">
                    @Html.HiddenFor(model => Model.MileStoneID)
                    <div class="col-sm-10 col-sm-offset-1" style="margin: 0 auto; float: none;">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Current Status</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            <div class="mad-select" style="margin-left:0px;width:300px;" id="StatusSelect">
                                <ul id="ddlStatus">
                                    <li data-value="2">In Progress</li>
                                    <li data-value="3">Done</li>
                                </ul>
                                @Html.HiddenFor(model => Model.MilesStoneStatus)
                            </div>
                        </div>
                        <div class="gap_20"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <input type="submit" value="SAVE" class="button_blue button_100">
            }
        </div>
    </div>
</div>

Reelae/Areas/Student/Views/MileStones/_markDone.cshtml
@model IEnumerable<ReelaeDataAccessLayer.MileStone>
@{
    var milestones = Model.ToList();
}
<div class="modal" id="markDoneModelBox" tabindex="-1" role="dialog" aria-labelledby="markDoneLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="material-icons">clear</i></button>
                <h4 class="modal-title" id="markDoneLabel">Mark Done</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table jambo_table bulk_action mb_0">
                        <thead>
                            <tr class="headings">
                                <th class="bulk-actions" colspan="5"> <a class="antoo" style="color:#7f8fa4; font-weight:400;"> ( <span class="action-cnt"> </span> ) </a></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var milestone in milestones)
                            {
                                <tr class="even pointer">
                                    <td class="a-center "><input type="checkbox" class="flat" name="table_records"></td>
                                    <td class="name">@milestone.MileStoneName</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <input type="submit" value="SAVE" class="button_blue button_100">
            @Html.Hidden("hdn_count",milestones.Count())
        </div>
    </div>
</div>

Reelae/Areas/Student/Views/MileStones/_newMilestone.cshtml
@model Reelae.Areas.Student.Models.newMilestoneViewModel
@{
    var _members = Model.Memebers.ToList();
}
<div class="modal" id="newMilestoneModelBox" tabindex="-1" role="dialog" aria-labelledby="newMilestoneLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="material-icons">clear</i></button>
                <h4 class="modal-title" id="newMilestoneLabel">New Milestone For @ViewBag.AssignmentName</h4>
            </div>
            @using (Ajax.BeginForm("addNewMilestone", "MileStones", new { area = "Student" }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "onMilestoneSucess", OnFailure = "onMilestoneFailure", OnBegin = "onMilestoneBegin" }))
            {
                <div class="modal-body">
                    @Html.Hidden("AssignmentDueDate")
                    @Html.HiddenFor(model => Model.milestone.MileStoneID)
                    <div class="col-sm-10 col-sm-offset-1" style="margin: 0 auto; float: none;">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Milestone Name</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            @Html.TextBoxFor(model => Model.milestone.MileStoneName, new { @class = "form-control brd_radius-4", id = "txt_name", placeholder = "Add milestone name here", maxlength = "100" })
                        </div>
                        <div class="gap_20"></div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Task Description</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            @Html.TextAreaFor(model => Model.milestone.TaskDescription, new { @class = "form-control brd_radius-4", id = "txt_descr", placeholder = "Add task description here", rows = "6", maxlength = "5000" })
                        </div>
                        <div class="gap_20"></div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Start Date</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            <div class="controls">
                                <div class="row">
                                    <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                                        @Html.TextBoxFor(model => Model.milestone.StartDate, new { @class = "form-control brd_radius-4 has-feedback-left pop_date", id = "txt_sdate", aria_describedby = "spanAddSubjectStartDate" })
                                        <input name="hdn_StartDate" id="hdn_StartDate" type="hidden" value="@Model.milestone.StartDate" />
                                        <span class="fa fa-calendar form-control-feedback left" aria-hidden="true"></span>
                                        <span id="spanStartDate" class="sr-only">(success)</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Due Date</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            <div class="controls">
                                <div class="row">
                                    <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                                        @Html.TextBoxFor(model => Model.milestone.endDate, new { @class = "form-control brd_radius-4 has-feedback-left pop_date", id = "txt_edate", aria_describedby = "spanAddSubjectStartDate" })
                                        <input name="hdn_DueDateTime" id="hdn_DueDateTime" type="hidden" value="@Model.milestone.endDate" />
                                        <span class="fa fa-calendar form-control-feedback left" aria-hidden="true"></span>
                                        <span id="spanDueDate" class="sr-only">(success)</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="gap_20"></div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Assign to</label><span style="color:red;font-size: 12px;">*</span>
                            <div class="clearfix"></div>
                            <div class="mad-select" style="margin-left:0px;width:300px;" id="MemberSelect">
                                <ul id="ddlMember">
                                    @foreach (var _member in _members)
                                    {
                                        <li data-value="@_member.MemberId"><a href="javascript:;" class="user-profile"> <img src="@(_member.UserPicUrl==null?Url.Content("~/Content/images/student.jpg"):Url.Content(_member.UserPicUrl))" alt="">@_member.NAME.Trim()</a></li>
                                    }
                                </ul>
                                @Html.HiddenFor(model => Model.milestone.StudentId)
                            </div>
                        </div>
                        @Html.HiddenFor(model=>Model.milestone.AssignmentID)
                        <div class="gap_20"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                    <input type="submit" value="SAVE" class="button_blue button_100">
            }
        </div>
    </div>
</div>