Reelae/Areas/Admin/Controllers/MemberController.cs
using Reelae.Areas.Admin.Models;
using Reelae.Controllers;
using Reelae.Filters;
using Reelae.Repositories;
using Reelae.Utilities;
using ReelaeBusinessLayer.Utilities;
using ReelaeDataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Net;

namespace Reelae.Areas.Admin.Controllers
{
    public class MemberController : Controller
    {
        IUserRepository _userRepo;
        ILogRepository _dbLogrepo;

        ISubjectStudentRepository _subjectStudentRepository;
        ISubjectTeacherRepository _subjectTeacherRepository;


        private ApplicationUserManager _userManager;
        private IAspnetUsersRepository _aspNetUserrepo;

        public MemberController(IUserRepository __userRepo, ILogRepository __dbLogrepo, IAspnetUsersRepository __aspNetUserrepo, ISubjectStudentRepository __subjectStudentRepository, ISubjectTeacherRepository __subjectTeacherRepository)
        {
            _userRepo = __userRepo;
            _dbLogrepo = __dbLogrepo;
            _aspNetUserrepo = __aspNetUserrepo;

            _subjectStudentRepository = __subjectStudentRepository;
            _subjectTeacherRepository = __subjectTeacherRepository;
        }
        public MemberController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        // GET: Admin/Member
        public ActionResult Index()
        {
            return View();
        }

        [checkSessionAlive]
        [HttpPost]
        public ActionResult getMembersGridView(int id)
        {
            try
            {
                int _InstutionID = Session["Institution"] != null ? Convert.ToInt32(Session["Institution"]) : 0;
                ViewBag.Id = id;
                return PartialView("_MembersGridView", _userRepo.GetAll(_InstutionID, id));
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserName"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message }; new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = MasterConstants.SOMEPROBLEMOccurred
                });
                //return RedirectToAction("Login", "Home", new { area = "" });
            }
        }

        [checkSessionAlive]
        public ActionResult getEditMembersView(int id)
        {
            try
            {
                return PartialView("_editMember", _userRepo.getUserDetail(id));
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserName"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message }; new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = MasterConstants.SOMEPROBLEMOccurred
                });
                //return RedirectToAction("Login", "Home", new { area = "" });
            }
        }

        [checkSessionAlive]
        [HttpPost]
        public async Task<ActionResult> SaveEditMember(re_getUserDetails_sp_Result model)
        {
            try
            {
                var user = await UserManager.FindByIdAsync(model.UserMemberShipID);
                bool _exitingAccountStatus = user.isEnabled;
                if (user != null)
                {                   
                    //code added by Anshul
                    if (!model.isEnabled && model.isEnabled!= user.isEnabled)
                    {
                        if (model.type.ToLower().Equals("student"))
                        {
                            if (_subjectStudentRepository.IsStudentMappedWithAnySubject(model.UserID))
                            {
                                return this.Json(new
                                {
                                    EnableError = true,
                                    ErrorTitle = MasterConstants.ERRORTITLE,
                                    ErrorMsg = "This user is mapped with a subject" + "#" + model.UserID + "#" + user.Id + "#" + model.type
                                });
                            }
                        }
                        else
                        {
                            if (_subjectTeacherRepository.IsTeacherMappedWithAnySubject(model.UserID))
                            {
                                return this.Json(new
                                {
                                    EnableError = true,
                                    ErrorTitle = MasterConstants.ERRORTITLE,
                                    ErrorMsg = "This user is mapped with a subject" + "#" + model.UserID + "#" + user.Id + "#" + model.type
                                });
                            }
                        }
                    }

                    //end code added by Anshul
                    user.isEnabled = model.isEnabled;
                    if (_aspNetUserrepo.update(user.Id, user.isEnabled))
                    {
                        if (model.isEnabled != _exitingAccountStatus)
                        {
                            var callbackUrl = Url.Action("Login", "Home", null, protocol: Request.Url.Scheme);
                            string status = String.Empty;
                            status = model.isEnabled == true ? "activated" : "deactivated";
                            string mailbody = Reelae.Utilities.EmailHtml.getAccountStatusHtml(model.Name, model.Email, callbackUrl, status);
                            Reelae.Utilities.Mail.SendMail(model.Email, "Reeale account is now " + status, mailbody);
                        }
                       _userRepo.EditUserNameAndEmail(model.UserID, model.Name, model.Email);
                        var result = UserManager.UpdateAsync(user);
                        return this.Json(new
                        {
                            EnableSuccess = true,
                            SuccessTitle = MasterConstants.SUCCESSTITLE,
                            SuccessMsg = MasterConstants.SAVESUCCESSFULLY + MasterConstants.SEPERATOR_SYMBOL + model.type
                        });
                    }
                    else
                    {
                        return this.Json(new
                        {
                            EnableError = true,
                            ErrorTitle = MasterConstants.ERRORTITLE,
                            ErrorMsg = "Users does not exists!"
                        });
                    }
                }
                else
                {
                    return this.Json(new
                    {
                        EnableError = true,
                        ErrorTitle = MasterConstants.ERRORTITLE,
                        ErrorMsg = "Users does not exists!"
                    });

                }
            }
            catch (Exception ex)
            {
                ReelaeDataAccessLayer.ErrorLog obj = new ReelaeDataAccessLayer.ErrorLog() { PageName = this.RouteData.Values["controller"].ToString(), MethodName = this.RouteData.Values["action"].ToString(), BrowserVersion = Request.Browser.Browser, CreatedBy = Session["UserName"].ToString(), CreatedDate = DateTime.UtcNow, Description = ex.Message }; new ErrorLogger(_dbLogrepo).WriteDBLog(obj, ex);
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return this.Json(new
                {
                    EnableError = true,
                    ErrorTitle = MasterConstants.ERRORTITLE,
                    ErrorMsg = MasterConstants.SOMEPROBLEMOccurred
                });
            }
        }






        [checkSessionAlive]
        public ActionResult SaveEditMemberActiveOrInactive(int id,string uId,string type)
        {
            var user =  UserManager.FindById(uId);
            if (user != null)
            {
                //if (type.ToLower() == "student")
                //{
                //    _subjectStudentRepository.removeStudentById(id);
                //}
                //else {
                //    _subjectTeacherRepository.removeTeacherById(id);
                //}
               
                if (_aspNetUserrepo.update(user.Id, false))
                {
                    user.isEnabled = false;

                    var result = UserManager.UpdateAsync(user);
                    string mailbody = EmailHtml.getAccountStatusHtml(user.Name, user.Email,"", "deactivated");
                    Mail.SendMail(user.Email, "Reeale account is now deactivated", mailbody);
                    return this.Json(new
                    {
                        EnableSuccess = true,
                        SuccessTitle = MasterConstants.SUCCESSTITLE,
                        SuccessMsg = MasterConstants.SAVESUCCESSFULLY + MasterConstants.SEPERATOR_SYMBOL + type
                    });
                }
                else
                {

Reelae/Areas/Admin/Views/Member/_MembersGridView.cshtml
@model IEnumerable<ReelaeDataAccessLayer.re_getInstituteMembers_sp_Result>
@{
    var _membersList = Model.ToList();
    string type = string.Empty;
    if (_membersList.Count > 0)
    {
        type = _membersList.FirstOrDefault().type;
    }
    int activeCount = _membersList.ToList().Where(r => r.isEnabled == true).Count();
    int inactiveCount = _membersList.ToList().Where(r => r.isEnabled == false).Count();
}

<style>
    .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
     display: block; 
}
</style>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 mrg_t_10 pad_lr-0">
        <div class="dashboard_graph pd_b-0">
            <div class="row x_title mrb_b-0">
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <h3>@type</h3>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12 text-center lh_30 txt_l-blue xs-left">
                    <i class="fa fa-user-o" aria-hidden="true"></i> @_membersList.Count() Members
                    @*<div class="clearfix"></div>*@
                    ( @activeCount Active and @inactiveCount Inactive)
                </div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="pad_lr-30" data-simplebar="init" style="height: 400px;max-width: 100%;" id="divMembersGrid">
        @*<div class="simplebar-track vertical" style="visibility: visible;"><div class="simplebar-scrollbar" style="top: 2px; height: 68px;"></div></div>
        <div class="simplebar-track horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar"></div></div>*@
        @*<div class="simplebar-scroll-content" style="margin-right: -20px;padding-right: 20px">*@
            <div class="simplebar-content">

                <div class="x_panel" style="padding-bottom: 0px;  margin-top: 30px;">
                    <div class="x_content">
                        @*<div class="table-responsive">*@
                        <div class="">
                            <table class="table table-striped" style="margin-bottom: 10px;" id="tblMemberGrid">
                                <thead>
                                    <tr>
                                        @*<th>type</th>*@
                                        <th style="vertical-align:top;">Member Code</th>
                                        <th style="vertical-align:top;">Name</th>
                                        <th style="vertical-align:top;">Email</th>
                                        @*<th style="white-space: nowrap;">Join Date</th>*@
                                        <th style="vertical-align:top;">Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (_membersList != null)
                                        {
                                            if (_membersList.Count() > 0)
                                            {
                                                foreach (var _member in _membersList)
                                                {
                                                    <tr onclick="getEditMembersView(@_member.UserID)">
                                                        <td>
                                                            @(string.IsNullOrEmpty(_member.UserCode) ? "" : _member.UserCode)
                                                        </td>
                                                        <td>
                                                            <ul class="list-unstyled top_profiles scroll-view">
                                                                <li class="media event">
                                                                    <a href="javascript:;" class="user-profile pull-left">
                                                                        @if (_member.UserPicUrl != null && _member.UserPicUrl != "")
                                                                        {
                                                                            <img src="@Url.Content(_member.UserPicUrl)" alt="...">
                                                                        }
                                                                        else
                                                                        {
                                                                            if (ViewBag.Id == 1)
                                                                            {
                                                                                <img src="@Url.Content("~/Content/images/teacher.jpg")" alt="">
                                                                            }
                                                                            else
                                                                            {
                                                                                <img src="@Url.Content("~/Content/images/student.jpg")" alt="">
                                                                            }
                                                                        }
                                                                    </a>
                                                                    <div class="media-body">
                                                                        <a class="title" href="#!" data-toggle="modal" data-target="#myModal11" style="padding-top: 12px; display: inline-block;" style="cursor:default">@_member.Name @_member.Surname</a>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </td>
                                                        <td>@_member.Email</td>
                                                        @if (_member.isEnabled)
                                                        {
                                                            @*<td class="pos-rel"><a href="#!" class="sm_btn btn_org mrg_t-4" data-toggle="modal" data-target="#" style="width:65px;">Active</a> </td>*@
                                                            <td style="width:20%" class="pos-rel"><a href="#!" class="sm_btn btn_green mrg_t-4" data-toggle="modal" data-target="#" style="width:65px;">Active</a> </td>
                                                        }
                                                        else
                                                        {
                                                            @*<td class="pos-rel"><a href="#!" class="sm_btn btn_green mrg_t-4" data-toggle="modal" data-target="#" style="width:65px;">Inactive</a> </td>*@
                                                            <td style="width:20%" class="pos-rel"><a href="#!" class="sm_btn btn_org mrg_t-4" data-toggle="modal" data-target="#" style="width:65px;">Inactive</a> </td>
                                                        }
                                                        <td class="text-right">
                                                            <a href="#!" data-toggle="modal" data-target="#" class="btn_blue mml-0 min_w-155 text-center">Edit</a>
                                                        </td>
                                                    </tr>

                                                }
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td colspan="4">
                                                        <label>No members are found.</label>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        @*</div>*@
    </div>
    <div class="clearfix"></div>
</div>

Reelae/Areas/Admin/Views/Member/_editMember.cshtml
@model ReelaeDataAccessLayer.re_getUserDetails_sp_Result
<div class="modal" id="editMemberModalBox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="material-icons">clear</i></button>
                <h4 class="modal-title" id="myModalLabel">Edit Detail</h4>
            </div>

            @using (Ajax.BeginForm("SaveEditMember", "Member", new { area = "Admin" }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "onEditSucess", OnFailure = "onEditFailure", OnBegin = "onEditBegin" }))
            {
                <div class="modal-body">
                    <div class="col-sm-10 col-sm-offset-1" style="margin: 0 auto; float: none;">
                        <div class="user_img col-xs-12 col-sm-12 text-center" style="margin-top: 0px;">
                            @if (Model.UserPicUrl != null)
                            {
                                <img src="@Url.Content(Model.UserPicUrl)" alt="..." class="img-circle img-responsive">
                            }
                            else
                            {
                                if (Model.type.StartsWith("T"))
                                {
                                    <img src="@Url.Content("~/Content/images/teacher.jpg")" alt="..." class="img-circle img-responsive">

                                }
                                else
                                {
                                    <img src="@Url.Content("~/Content/images/student.jpg")" alt="..." class="img-circle img-responsive">

                                }
                            }
                        </div>
                        <div class="form-group">
                            <label>Member Code</label>
                            <div class="clearfix"></div>
                            @Html.TextBoxFor(model => model.UserCode, new { @readonly = "readonly", @class = "form-control brd_radius-4", style = "background-color: #fff;font-weight:bold;", @id = "editmemberCode", onchange = "onChangeValidate(this)", maxlength = "25" })
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            <div class="clearfix"></div>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control brd_radius-4", placeholder = "Name", style = "background-color: #fff;", @id = "editmemberName", onchange = "onChangeValidate(this)", maxlength = "25" })
                        </div>
                        <div class="gap_20"></div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email</label>
                            <div class="clearfix"></div>
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control brd_radius-4", placeholder = "Email", style = "background-color: #fff;", @id = "editmemberEmail", onchange = "onChangeValidate(this)", maxlength = "100" })
                        </div>
                        <div class="gap_20"></div>
                        <div class="gap_20" style="height: 1px;"></div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(model => model.isEnabled, new { @class = "flat" })
                                    @Html.HiddenFor(model => model.UserMemberShipID)
                                    @Html.HiddenFor(model => model.type)
                                    @Html.HiddenFor(model => model.UserID)
                                    Activate
                                </label>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <input type="submit" value="Finish" class="button_blue button_100">
            }
        </div>
    </div>
</div>